#!/usr/bin/env ruby

require "rubygame"

include Rubygame

RESOLUTION = [1280, 800]
SHIP = [32, 32]
SPIKE = SHIP
GOON = [8, 8]

GOON_MAX_SPEED = 500.0
SHIP_MAX_SPEED = GOON_MAX_SPEED
GOON_ACCEL = 1200.0
SHIP_ACCEL = 2000.0
SLOWDOWN = 800.0

PUSH = 6
SPIKE_PUSH = 30

SHIP_HEALTH = 3
SHIP_INVULNERABLE = 10

STATUS_FONT = "FreeSans.ttf"
STATUS_SIZE = 16
STATUS_COLOR = [250,250,250]
STATUS_Y = 5
STATUS_HEALTH_X = 5
STATUS_GOONS_X = 1200

TTF.setup()
ttfont_path = File.join(File.dirname(__FILE__), STATUS_FONT)
FONT = TTF.new( ttfont_path, STATUS_SIZE )

LEVEL_FILE = "levels.yaml"
SELECT_COLOR = [250,250,50]
MENU_Y = 300

STATE_TITLE = 0
STATE_MENU = 1
STATE_GAME = 2
STATE_DIRECTIONS = 3
STATE_WIN = 4
STATE_LOSE = 5

MAGIC_HOOKS = { Rubygame::EventTriggers::YesTrigger.new() => :handle }

GAME_RUNNING = 0
GAME_WON = 1
GAME_LOST = 2
